export class Constants {
    public static ErrorType = {
        "REQUIRED": "REQUIRED",
        "MAXLENGTH": "MAXLENGTH",
        "PATTERN": "PATTERN",
        "INVALID": "INVALID",
        "MAXNUMBER": "MAXNUMBER",
        "MAXVALUE": "MAXVALUE"
    }

    public static PatternTypes = {
        "ONLYTEXT": "ONLYTEXT",
        "ONLYNUMERIC": "ONLYNUMERIC",
        "ONLYALPHANUMBERIC": "ONLYALPHANUMBERIC",
        "ONLYDATETIME": "ONLYDATETIME",
        "ALPHANUMERICSPECIAL_ERROR": "ALPHANUMERICSPECIAL_ERROR",
        "ALPHANUMERICSPECIAL_MORE_ERROR": "ALPHANUMERICSPECIAL_MORE_ERROR",
        "PORTNUMBER_ERROR": "PORTNUMBER_ERROR",
        "MACADDRESS_ERROR": "MACADDRESS_ERROR",
        "ONLYIPADDRESS": "ONLYIPADDRESS",
        "DECIMALS_ERROR": "DECIMALS_ERROR",
        "GREATERTHANZERO": "GREATERTHANZERO",
        "EMAIL_ERROR": "EMAIL_ERROR",
        "WEBSITE_ERROR": "WEBSITE_ERROR",
        "COORDINATES_ERROR": "COORDINATES_ERROR"
    }
}
